FROM jenkins/jenkins:lts

USER root
RUN apt-get update && apt-get install -y     docker.io     make     g++     curl
RUN apt-get install -y sudo && \
    echo "jenkins ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

USER jenkins
